// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHC9V5Df-ng6CykP7KfNHGtTCBYGXp-QU',
    appId: '1:518358208530:web:418089cc7044fb0ca048cb',
    messagingSenderId: '518358208530',
    projectId: 'ecoguia-84d7c',
    authDomain: 'ecoguia-84d7c.firebaseapp.com',
    storageBucket: 'ecoguia-84d7c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs0ac4qGpjchkYEqKKBajst6ZgxLGvJu4',
    appId: '1:518358208530:android:b0d6bfdac13eda85a048cb',
    messagingSenderId: '518358208530',
    projectId: 'ecoguia-84d7c',
    storageBucket: 'ecoguia-84d7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4CS_guVY71qfamz0C0Igm0gAjNPVYSgw',
    appId: '1:518358208530:ios:17adc7dd60eec0fba048cb',
    messagingSenderId: '518358208530',
    projectId: 'ecoguia-84d7c',
    storageBucket: 'ecoguia-84d7c.firebasestorage.app',
    iosBundleId: 'com.example.ecoGuia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4CS_guVY71qfamz0C0Igm0gAjNPVYSgw',
    appId: '1:518358208530:ios:17adc7dd60eec0fba048cb',
    messagingSenderId: '518358208530',
    projectId: 'ecoguia-84d7c',
    storageBucket: 'ecoguia-84d7c.firebasestorage.app',
    iosBundleId: 'com.example.ecoGuia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHC9V5Df-ng6CykP7KfNHGtTCBYGXp-QU',
    appId: '1:518358208530:web:aab94e70ad1df0eba048cb',
    messagingSenderId: '518358208530',
    projectId: 'ecoguia-84d7c',
    authDomain: 'ecoguia-84d7c.firebaseapp.com',
    storageBucket: 'ecoguia-84d7c.firebasestorage.app',
  );
}
